version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
      - PORT=3000

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: alves
      POSTGRES_PASSWORD: 202627
      POSTGRES_DB: backend_contacts_manager
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data